### ISSUE TITLE
Percentage of code saved

### ISSUE THREAD

**Issue by drcmda** [pmndrs/threejs-journey#11]
Is there any chance of giving these thumbnails a rough percentage of how much code has fallen away if compared against the original? It's probably not super precise and subjective but as a rough orientation it would be useful. 

Also, nice work, looking better and better! 👍

**Comment by hazem3500** [comment]
Hmmmmm 🤔, not sure how to determine the percentage.
The examples aren't a 1:1 replica of the course, I kind of do my own spin-off on it and I'm also using drei while the course examples does everything from scratch, so the percentage wouldn't make much sense 😅

I'll give it some thought, maybe we can host the original example beside the r3f ones so people can compare, @drcmda what do you think?

**Comment by drcmda** [comment]
the original examples side by side would be wonderful as well

**Comment by hazem3500** [comment]
@drcmda will close this issue in favour of #12
