### ISSUE TITLE
Some Codesandbox examples don't work

### ISSUE THREAD

**Issue by zipme** [pmndrs/threejs-journey#14]
When visiting 
- https://journey.pmnd.rs/classic-techniques/scroll-based-animation  => 
```
Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ScrollBasedAnimation`.
```
- https://journey.pmnd.rs/basics/textures => `Could not load texture/roughness.jpg: undefined`
- https://journey.pmnd.rs/classic-techniques/haunted-house => `ModuleNotFoundError`
- ...

**Comment by hazem3500** [comment]
Thanks @zipme will check it out 👍

**Comment by hazem3500** [comment]
Fixed 👍, some sandboxes have an issue with undefined texture, not sure why.

Will contact codesandbox

**Comment by zipme** [comment]
@hazem3500 wow that's fast! Thank you so much!

**Comment by hazem3500** [comment]
> @hazem3500 wow that's fast! Thank you so much!

Oh, It was just a quick fix 😁
