### ISSUE TITLE
How to run example 'Level1'

### ISSUE THREAD

**Issue by mshumako** [pmndrs/threejs-journey#21]
Hello,

I am trying to run the Level1 example. But I see the error in the console and it's impossible to rotate the camera
What I did:
1) Downloaded https://github.com/pmndrs/threejs-journey/tree/main/examples/levels/Level1
2) `npm install`
3) `npm start`

Error:
```
./node_modules/three-stdlib/objects/Lensflare.js
Attempted import error: 'FramebufferTexture' is not exported from 'three'.
```
Can you please help me run this example? If it's working on your environment then could you please share the package-lock.json ?

**Comment by hazem3500** [comment]
It should just work from this link https://journey.pmnd.rs/levels/1 but apparently there's an error 😅, will check it out and get back to you 👍

**Comment by hazem3500** [comment]
Doesn't going to https://journey.pmnd.rs/levels/1 work?
You can fork it by clicking **"Edit Sandbox"**

**Comment by mshumako** [comment]
It works in sandbox but doesn't work if you want use it locally for example to change something. Have you tried running it using the 3 steps I described in the first post?

I tried on 3 different PC, same error everywhere

**Comment by mshumako** [comment]
Seems like it's the problem of the third-party lib. Found the same issue here https://github.com/mrdoob/three.js/issues/23349

**Comment by mshumako** [comment]
I updated the package.json to fix my issue:
```
"@react-three/drei": "^8.8.0",
"@types/three": "^0.137.0",
 "three": "^0.137.0"
```
Now it works :)
