### ISSUE TITLE
Integrate with codesandboxer

### ISSUE THREAD

**Issue by hazem3500** [pmndrs/threejs-journey#4]
We can use [codesandboxer](https://github.com/codesandbox/codesandboxer) to make examples be opened in [codesandbox](https://codesandbox.io/) so people are able to view and remix the code

### Note
We'll need to check if **codesandboxer** will be able to take static files from `public` or do they need to be imported relatively in the component (Related #3)

**Comment by gsimone** [comment]
Check out the way I did this in this repo https://github.com/pmndrs/maath/tree/main/demo/src/sandboxes
each of the dirs is a self-sufficient sandbox that can be used via githubbox

As an example, you can see the linked sandboxes in the README https://github.com/pmndrs/maath

bonus, the sandboxes can also be imported in the dev environment (I do that in maath, we also have leva setup this way)
