### ISSUE TITLE
Integrate with CI/CD tool

### ISSUE THREAD

**Issue by hazem3500** [pmndrs/threejs-journey#7]
We can use [vercel](https://vercel.com/) or [netlify](https://www.netlify.com/) to deploy the website

**Comment by gsimone** [comment]
We have a vercel org, DM me on discord when you want to set this up ( gsimone#8422 )

**Comment by hazem3500** [comment]
> We have a vercel org, DM me on discord when you want to set this up ( gsimone#8422 )

Will do 👍, will be AFK though for the next 4-5 days, so I'll continue when I'm back 😁

**Comment by drcmda** [comment]
its up a journey.pmnd.rs
